version: "3"

services:
  lilurl:
    container_name: lilurl
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - front-tier
      - back-tier
    # depends_on:
    #   - db

  # db:
  #   container_name: db
  #   image: alpine:latest
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: lilurl
  #     MYSQL_USER: lilurl
  #     MYSQL_PASSWORD: lilurl
  #   ports:
  #     - "3306:3306"
  #   networks:
  #     - back-tier

  proxy:
    container_name: lilurl-proxy
    image: nginx:alpine
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - front-tier
    depends_on:
      - lilurl

networks:
  front-tier: {}
  back-tier: {}
