name: "ci"

on: [push]

jobs:
  deps:
    name: Setup Cache
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: install dependencies
        uses: jetify-com/devbox-install-action@v0.12.0
        with:
          enable-cache: 'true'
          refresh-cli: 'false'
          devbox-version: '0.16.0'

      - name: Download dependencies
        run: devbox run deps

  lint:
    name: Run linter
    runs-on: ubuntu-latest
    needs:
      - deps
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: install dependencies
        uses: jetify-com/devbox-install-action@v0.12.0
        with:
          enable-cache: 'true'
          refresh-cli: 'false'
          devbox-version: '0.16.0'

      - name: Run linter
        run: devbox run lint

  test:
    name: Run tests
    runs-on: ubuntu-latest
    needs:
      - deps
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: install dependencies
        uses: jetify-com/devbox-install-action@v0.12.0
        with:
          enable-cache: 'true'
          refresh-cli: 'false'
          devbox-version: '0.16.0'

      - name: Run tests
        run: devbox run test


  intergration-tests:
    name: Run integration tests
    runs-on: ubuntu-latest
    needs:
      - deps
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
      - name: install dependencies
        uses: jetify-com/devbox-install-action@v0.12.0
        with:
          enable-cache: 'true'
          refresh-cli: 'false'
          devbox-version: '0.16.0'

      - name: Run integration tests
        run: devbox run integration-test

  build-push:
    name: Build, Push
    runs-on: ubuntu-latest
    needs:
      - test
      - lint
      - intergration-tests
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: install dependencies
        uses: jetify-com/devbox-install-action@v0.12.0
        with:
          enable-cache: 'true'
          refresh-cli: 'false'
          devbox-version: '0.16.0'


      - name: Build
        run: devbox run build-ar
        env:
          GAR: ${{ vars.GCP_REGISTRY}}
